name: Docker Sync

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC (convert to Shanghai time if needed)
  workflow_dispatch:
  push:
    paths:
      - "images.json"

jobs:
  sync_and_commit:
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY_NAMESPACE: ${{ secrets.ALIYUN_REGISTRY_NAMESPACE }}
      WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
      AUTH_JSON_BASE64: ${{ secrets.AUTH_JSON_BASE64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Decode AUTH_JSON_BASE64
        run: echo "${{ secrets.AUTH_JSON_BASE64 }}" | base64 --decode > auth.json

      - name: Prepare Docker Sync Scripts
        run: |
          python3 gen_images_compat.py

      - name: check file exists
        run: |
          if [ ! -f images_compat.json ]; then
            echo "images_compat.json not found, exiting."
            exit 1
          fi

      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.json
          images_file: ./images_compat.json
          version: latest
          proc: 6
