name: Docker Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'images.json'

jobs:
  sync_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ALIYUN_REGISTRY_NAMESPACE: ${{ secrets.ALIYUN_REGISTRY_NAMESPACE }}
      WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous digest_records.json
        uses: actions/download-artifact@v4
        with:
          name: digest-records
          path: .
        continue-on-error: true

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Login to Aliyun Container Registry
        run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_REGISTRY_USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com

      - name: Run sync script
        run: python sync_images.py

      - name: Upload updated digest_records.json
        uses: actions/upload-artifact@v4
        with:
          name: digest-records
          path: digest_records.json
          retention-days: 7

      - name: Commit and push changes
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(sync): update digest_records and status"
          branch: master
          commit_user_name: github-actions
          commit_user_email: actions@github.com
          files: digest_records.json,status.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
